name: Build Android APK (Buildozer)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Configuración explícita de Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            zip \
            unzip

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install "cython<3.0.0"
          pip install "buildozer"
          

      - name: Clean previous build cache
        run: |
          buildozer android clean || true

      - name: Build APK
        # =========================================================================
        # COMENTARIO: Agregamos el bloque 'env' justo debajo de 'run' en este paso.
        # QUÉ HACE: Obliga a Buildozer a utilizar la versión 25b del NDK de Android, 
        # evitando que el sistema tome por defecto una versión más nueva del servidor 
        # que rompe la compilación de las librerías nativas (como SDL2 y FreeType).
        # =========================================================================
        run: |
          buildozer -v android debug
        env:
          ANDROID_NDK_HOME: /home/runner/.buildozer/android/platform/android-ndk-r25b # <-- AQUÍ SE INGRESÓ

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk